### ISSUE TITLE
Unable to run a script with runscript

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#110]
I am trying to run a script with RunScript - the script runs from a UNC path. Is that possible? The RunScript creates the script file in the temp directory correctly, it will just not run. It is just \\servername\path\script.cmd ....If I run that script file locally on the server it does run. My script is not the problem, as it has been running for a few years through a scheduled task. There are no errors:
Result

    [2015-12-21 22:32:11] Success - connect to remote Windows machine x.x.x.x
    [2015-12-21 22:32:12] Success - send file to remote machine
    [2015-12-21 22:32:12] Success - trigger batch script in VM

    System.Management.ManagementBaseObject

Thanks for any assistance!

**Comment by bvi1998** [comment]
I decided to do what I was originally attempting, which is to schedule a task from WebCommander to run the command.
The entire problem came down to the fact that when executing the schtasks.exe, I needed to give the full path C:\Windows\System32\schtasks.exe .... ugh!

**Comment by 9whirls** [comment]
You could run a script from UNC share via the runScript command. The tricky part is that you need to mount the UNC (also via the same runScript command) first. For instance, in order to run 
\\share\script.bat
you should run the following to commands instead
net use \\share <password> /user:<username>
\\share\script.bat

**Comment by bvi1998** [comment]
ok thanks Jerry.
