### ISSUE TITLE
Length of time to run the script

### ISSUE THREAD

**Issue by bvi1998** [vmware/webcommander#207]
Hi, When I run my script from Webcommander locally it runs in 3 seconds. When it run it with Webcommander it takes 39 seconds. I just going out and getting free IP addresses from an IPAM server, then registering the server in DNS. I am using the option $runFromWeb = $true, so the script is quite simple. Has anyone experienced this? I am using two CIM sessions, one to the IPAM server and one to the DC.
Thanks!

**Comment by 9whirls** [comment]
```
. .\objects.ps1
$start = get-date
start-sleep 10
$end = get-date
$duration = ($end - $start).totalseconds
writeCustomizedMsg "Info - execution time $duration seconds "
```
Please try this script from webcommander and see how much time it takes.

**Comment by bvi1998** [comment]
Thanks I had done that before and it takes 39 seconds...

**Comment by bvi1998** [comment]
thanks it took 146 seconds

**Comment by 9whirls** [comment]
That means the real execution time is constantly 13 to 15 times of the expected execution time. And the problem is not in the script.

If this is caused by web commander, we should have observed it long ago. So I am pretty sure this is a server specific issue. I mean it only happens on your machine. I couldn't do further investigation without access to your server.

**Comment by bvi1998** [comment]
ok thanks!
