### ISSUE TITLE
urldecode

### ISSUE THREAD

**Issue by vLifeOfBrian** [vmware/webcommander#95]
Hey Jerry,

Just looking at the tech preview, and I see the urldecode still needs to be inserted into the powershell script. I have been struggling with webcommander adoption, because my engineers need to modify their scripts to get them to work with webcommander. Is there a way to create a php function, or something, that would read in the script, so the scripts don't require modification as long as they are returning an object? 

We are attempting to use webCommander to centralize and standardize script execution in the environment, but I would like to use the same scripts for other applications without modifying them. Since we have so many existing scripts, it would be preferred to not have to tailor them to work with webCommander beyond modifying the comments. 

Here is another php implementation for executing powershell scripts, and the scripts don't require modification. Don't know if you have seen it.

https://bitbucket.org/jasoooon/gumper/src/c4c1a2e9c9095655936d0323d02fa5272c8cb3c7?at=master

Don't know if its possible. PHP isn't my specialty, but thought I would see what your thoughts were? 

I like the way the new UI looks!

**Comment by 9whirls** [comment]
Hi Brian,

urldecode is adopted in Powershell scripts because PHP does urlencode to parameters input by users. This is how webcommander handles special characters that needs to be escaped. If you don't want to modify the existing scripts, you could just ask users to escape special characters when they input parameters in the web page. For instance, enter "` " for " " and "`$" for "$" etc. 

Another simple solution is to write a runner.ps1 as below

### start runner.ps1 ###
$cmd = @()
for ( $i = 0; $i -lt $args.count; $i++ ) {
  $cmd += [system.web.httputility]::urldecode($args[ $i ])
}
write-host $cmd.count
$cmd = $cmd -join " "

invoke-expression $cmd
### end runner.ps1 ###

Then you could pass existing script path and all parameters to runner.ps1.

Let me know if you need further assistance.

**Comment by vLifeOfBrian** [comment]
Hey Jerry,

Yeah, that has been my solution, so far, is to create a wrapper script for the scripts that we prefer to not be modified. 

Thanks!

**Comment by 9whirls** [comment]
Cool, I wish you would be a code contrutor too.

**Comment by vLifeOfBrian** [comment]
Actually, I do have a couple things I need to cleanup, and I'll submit them. 

I thought of something else for the new webCommander. What do you think about making it more RESTful? By RESTful I mean if you do a GET to webCommander it will list the services/scripts available, and if you do a GET on the service/script it returns a list of parameters. Then performing a POST to run the command passing the parameters with a JSON body. I know you can kinda do this now with the workflow script, but thought maybe it could be improved on.

We are using webCommander a lot of call powershell scripts as web services from other applications, so seeing more of a standard RESTful way to call the services would be cool.

**Comment by 9whirls** [comment]
Excellent toughts!
Currently, webcommander considers both GET and POST as script triggers. It returns parameters all the time.  
Since we could export command / workflow as JSON, it's intuitive to use the same JSON to trigger commands. I'm currently working on this feature.

**Comment by vLifeOfBrian** [comment]
Thanks Jerry!
